//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountType
    {
        public int IDAccountType { get; set; }
        public string TypeDescription { get; set; }
        public int IDAccount { get; set; }
        public byte[] Hide { get; set; }
        public string Meta { get; set; }
        public string Order { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
