//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceBridge
    {
        public int IDAttendance { get; set; }
        public int IDSinhVien { get; set; }
        public int IDAccount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Attendance Attendance { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
