//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.Accounts = new HashSet<Account>();
            this.Logs = new HashSet<Log>();
            this.Mistakes = new HashSet<Mistake>();
        }
    
        public int IDSinhVien { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public System.DateTime BirthDay { get; set; }
        public System.DateTime AttendDate { get; set; }
        public int AttendYear { get; set; }
        public int GraduateYear { get; set; }
        public string MSSV { get; set; }
        public int IDFalcuty { get; set; }
        public int IDContract { get; set; }
        public int IDRoom { get; set; }
        public string Order { get; set; }
        public string Meta { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<int> Hide { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mistake> Mistakes { get; set; }
        public virtual Room Room { get; set; }
    }
}
